name: Continuous Delivery

on:
  push:
    branches: [ "main" ] # Roda sempre que algo é aprovado e entra na main

jobs:
  deploy-alert:
    runs-on: ubuntu-latest

    steps:
      - name: Enviar Alerta de Deploy para o Discord
        uses: sarisia/actions-status-discord@v1
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          status: ${{ job.status }}
          content: " O código passou nos testes e o Deploy foi realizado com sucesso!"
          title: "Status do CD - Entrega Contínua"